/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Model.Model_Admin;
import Model.Model_Barang;
import Model.Model_BarangKeluar;
import Model.Model_DetBarangKeluar;
import Model.Model_Pemesan;
import TableMod.TableMod_BarangKeluar;
import TableMod.TableMod_DetBarangKeluar;
import config.koneksi;
import dao.DAO_BarangKeluar;
import dao.DAO_detBarangKeluar;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import service.Service_BarangKeluar;
import service.Service_DetBarangKeluar;

/**
 *
 * @author SyafiqUbai
 */
public class barang_keluar extends javax.swing.JPanel {

    private Service_BarangKeluar servis = new DAO_BarangKeluar();
    TableMod_BarangKeluar tblMod = new TableMod_BarangKeluar();

    private Service_DetBarangKeluar servis_det = new DAO_detBarangKeluar();
    TableMod_DetBarangKeluar tbl_det = new TableMod_DetBarangKeluar();

    private java.sql.Connection conn;

    public barang_keluar(String id) {
        initComponents();
        tbl_data.setModel(tblMod);
        tbl_detail.setModel(tbl_det);
//        btn_search.requestFocus();

        loadData();
        lb_ID.setText(id);
        lb_ID.setVisible(false);
        pn_detail.setVisible(false);
        conn = koneksi.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        scrollPaneWin111 = new scrollbarwin11.ScrollPaneWin11();
        tbl_data = new tablecustom.tablez();
        judul1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_tambah = new rojerusan.RSMaterialButtonRectangle();
        btn_hapus = new rojerusan.RSMaterialButtonRectangle();
        btn_batal = new rojerusan.RSMaterialButtonRectangle();
        tf_pencarian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_print = new rojerusan.RSMaterialButtonRectangle();
        pn_detail = new javax.swing.JPanel();
        scrollPaneWin112 = new scrollbarwin11.ScrollPaneWin11();
        tbl_detail = new tablecustom.tablez();
        judul3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tambahData = new javax.swing.JPanel();
        judul2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_tambah1 = new rojerusan.RSMaterialButtonRectangle();
        btn_clear = new rojerusan.RSMaterialButtonRectangle();
        btn_batal1 = new rojerusan.RSMaterialButtonRectangle();
        pn_dataUtama = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        t_kodeBK = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_tgl = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_idPemesan = new javax.swing.JTextField();
        t_unit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_pemesan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        t_kodeBarang = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        t_namaBarang = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        t_jumlah = new javax.swing.JTextField();
        btn_barang = new javax.swing.JButton();
        btn_tambahSem = new rojerusan.RSMaterialButtonRectangle();
        btn_hapussem = new rojerusan.RSMaterialButtonRectangle();
        btn_perbaruisem = new rojerusan.RSMaterialButtonRectangle();
        scrollPaneWin113 = new scrollbarwin11.ScrollPaneWin11();
        tbl_sementara = new tablecustom.tablez();
        lb_ID = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        tampilData.setBackground(new java.awt.Color(255, 255, 255));

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dataMouseClicked(evt);
            }
        });
        scrollPaneWin111.setViewportView(tbl_data);

        judul1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        judul1.setText("Data Barang Keluar");

        btn_tambah.setBackground(new java.awt.Color(0, 0, 255));
        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(153, 0, 0));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(0, 102, 0));
        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        tf_pencarian.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        tf_pencarian.setText("Search");
        tf_pencarian.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_pencarian.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_pencarianFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_pencarianFocusLost(evt);
            }
        });
        tf_pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pencarianActionPerformed(evt);
            }
        });
        tf_pencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_pencarianKeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search (1).png"))); // NOI18N

        btn_print.setBackground(new java.awt.Color(204, 204, 0));
        btn_print.setText("print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        pn_detail.setBackground(new java.awt.Color(255, 255, 255));

        tbl_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneWin112.setViewportView(tbl_detail);

        judul3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        judul3.setText("Detail Barang Keluar");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_detailLayout = new javax.swing.GroupLayout(pn_detail);
        pn_detail.setLayout(pn_detailLayout);
        pn_detailLayout.setHorizontalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneWin112, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(judul3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pn_detailLayout.setVerticalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_detailLayout.createSequentialGroup()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(judul3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPaneWin112, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(pn_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1))
                    .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        mainPanel.add(tampilData, "card2");

        tambahData.setBackground(new java.awt.Color(255, 255, 255));

        judul2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        judul2.setText("Tambah Pemesan");

        btn_tambah1.setBackground(new java.awt.Color(0, 0, 255));
        btn_tambah1.setText("TAMBAH");
        btn_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah1ActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(153, 0, 0));
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_batal1.setBackground(new java.awt.Color(0, 102, 0));
        btn_batal1.setText("BATAL");
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        pn_dataUtama.setBackground(new java.awt.Color(0, 153, 102));
        pn_dataUtama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kode Barang Keluar");

        t_kodeBK.setEditable(false);
        t_kodeBK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal Keluar");

        t_tgl.setEditable(false);
        t_tgl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout pn_dataUtamaLayout = new javax.swing.GroupLayout(pn_dataUtama);
        pn_dataUtama.setLayout(pn_dataUtamaLayout);
        pn_dataUtamaLayout.setHorizontalGroup(
            pn_dataUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dataUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_dataUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_kodeBK)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_dataUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_tgl)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_dataUtamaLayout.setVerticalGroup(
            pn_dataUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dataUtamaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pn_dataUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_dataUtamaLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_dataUtamaLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_kodeBK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBackground(new java.awt.Color(0, 153, 102));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PEMESAN");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ID Pemesan");

        t_idPemesan.setEditable(false);
        t_idPemesan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        t_unit.setEditable(false);
        t_unit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Unit Pemesan");

        btn_pemesan.setText("...");
        btn_pemesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pemesanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_idPemesan)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(t_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_pemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_idPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_pemesan))))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("BARANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Kode Barang");

        t_kodeBarang.setEditable(false);
        t_kodeBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Nama Barang");

        t_namaBarang.setEditable(false);
        t_namaBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Jumlah");

        t_jumlah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_barang.setText("...");
        btn_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_barangActionPerformed(evt);
            }
        });

        btn_tambahSem.setBackground(new java.awt.Color(0, 0, 255));
        btn_tambahSem.setText("TAMBAH SEMENTARA");
        btn_tambahSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahSemActionPerformed(evt);
            }
        });

        btn_hapussem.setBackground(new java.awt.Color(153, 0, 0));
        btn_hapussem.setText("HAPUS");
        btn_hapussem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapussemActionPerformed(evt);
            }
        });

        btn_perbaruisem.setBackground(new java.awt.Color(0, 102, 0));
        btn_perbaruisem.setText("PERBARUI");
        btn_perbaruisem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perbaruisemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_tambahSem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(t_kodeBarang)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_namaBarang)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_jumlah)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_perbaruisem, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_hapussem, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_barang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_tambahSem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_perbaruisem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_hapussem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tbl_sementara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Jumlah Barang"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_sementara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sementaraMouseClicked(evt);
            }
        });
        scrollPaneWin113.setViewportView(tbl_sementara);

        lb_ID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_ID.setText("ID");

        javax.swing.GroupLayout tambahDataLayout = new javax.swing.GroupLayout(tambahData);
        tambahData.setLayout(tambahDataLayout);
        tambahDataLayout.setHorizontalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahDataLayout.createSequentialGroup()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tambahDataLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pn_dataUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahDataLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahDataLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahDataLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(scrollPaneWin113, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                            .addGroup(tambahDataLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lb_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );
        tambahDataLayout.setVerticalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addComponent(scrollPaneWin113, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addComponent(pn_dataUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        mainPanel.add(tambahData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        String x = btn_tambah.getText();
        int row = tbl_data.getSelectedRow();
        if (x.equals("TAMBAH")) {

            mainPanel.removeAll();
            mainPanel.repaint();
            mainPanel.revalidate();

            mainPanel.add(tambahData);
            mainPanel.repaint();
            mainPanel.revalidate();

            judul2.setText("Tambah Pemesan");
            btn_tambah1.setText("SIMPAN");
            t_kodeBK.setText(servis.nomor());
            setTanggal();
            loadData();
        } else {
            int index = tbl_data.getSelectedRow();
            if (index != -1) {
                Model_BarangKeluar mod = tblMod.getData(tbl_data.convertRowIndexToModel(index));

                if (x.equals("UBAH")) {
                    dataTabel();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan diubah");
            }
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        String x = btn_clear.getText();
        if (x.equals("CLEAR")) {
            t_idPemesan.setText("");
            t_unit.setText("");
            t_kodeBarang.setText("");
            t_namaBarang.setText("");
            t_jumlah.setText("");
        } else {
            tampilPanel();
            loadData();
            resetForm();
        }
        btn_clear.setText("CLEAR");
        btn_batal1.setVisible(true);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah1ActionPerformed
        if (btn_tambah1.getText().equals("TAMBAH")) {
            btn_tambah1.setText("SIMPAN");
        } else if (btn_tambah1.getText().equals("SIMPAN")) {
            simpanData();
            simpanDet();
            loadData();
            resetForm();
            tampilPanel();
        } else if (btn_tambah1.getText().equals("PERBARUI")) {
            perbaruiData();
        }
    }//GEN-LAST:event_btn_tambah1ActionPerformed

    private void tf_pencarianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pencarianKeyPressed
        pencarian();
    }//GEN-LAST:event_tf_pencarianKeyPressed

    private void tf_pencarianFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_pencarianFocusGained
        String username = tf_pencarian.getText();
        if (username.equals("Search")) {
            tf_pencarian.setText("");
        }
    }//GEN-LAST:event_tf_pencarianFocusGained

    private void tf_pencarianFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_pencarianFocusLost
        String user = tf_pencarian.getText();
        if (user.equalsIgnoreCase("Search") || user.equalsIgnoreCase("")) {
            tf_pencarian.setText("Search");
        }
    }//GEN-LAST:event_tf_pencarianFocusLost

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
//        try {
//            String path = "src/report/laporan.jrxml";
//            JasperReport jasperReport = null;
//            SimpleDateFormat tgl = new SimpleDateFormat("dd-MM-yyyy");
//            
//            jasperReport = JasperCompileManager.compileReport(path);
//
//            HashMap<String, Object> par = new HashMap<>();
//            par.put("tglAwal", jDateChooser1.getDate());
//            par.put("tglAkhir", jDateChooser2.getDate());
//            JasperPrint print = JasperFillManager.fillReport(jasperReport, par, koneksi.getConnection());
//            JasperViewer viewer = new JasperViewer(print, false);
//            viewer.setVisible(true);
//        } catch (JRException ex) {
//            Logger.getLogger(barang_keluar.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_perbaruisemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perbaruisemActionPerformed
        perbaruiSementara();
    }//GEN-LAST:event_btn_perbaruisemActionPerformed

    private void btn_hapussemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapussemActionPerformed
        int index = tbl_sementara.getSelectedRow();
        if (index != -1) {
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                DefaultTableModel tb = (DefaultTableModel) tbl_sementara.getModel();
                tb.removeRow(tbl_sementara.getSelectedRow());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }//GEN-LAST:event_btn_hapussemActionPerformed

    private void btn_tambahSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahSemActionPerformed

        if (validasiInput() == true) {
            if (evt.getSource() == btn_tambahSem) {
                String kodeOnderdil = t_kodeBarang.getText();
                int jmh = Integer.parseInt(t_jumlah.getText());

                if (cekStok(kodeOnderdil, jmh)) {
                    DefaultTableModel tb = (DefaultTableModel) tbl_sementara.getModel();
                    tb.addRow(new Object[]{
                        t_kodeBarang.getText(),
                        t_namaBarang.getText(),
                        t_jumlah.getText(),});

                    JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan!");
                } else {
                    JOptionPane.showMessageDialog(this, "Stok Barang melebihi stok yang tersedia!", "Peringatan", JOptionPane.WARNING_MESSAGE);

                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan!");
        }
    }//GEN-LAST:event_btn_tambahSemActionPerformed

    private void tbl_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseClicked
//        btn_hapus.setVisible(true);
//        btn_batal.setVisible(true);
//        btn_print.setVisible(true);
        int row = tbl_data.getSelectedRow();
        String id = tbl_data.getValueAt(row, 0).toString();

        pn_detail.setVisible(true);
        List<Model_DetBarangKeluar> list = servis_det.getByid(id);
        tbl_det.setData(list);
    }//GEN-LAST:event_tbl_dataMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        pn_detail.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btn_pemesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pemesanActionPerformed
        boolean closable = true;
        dialog_pemesan p = new dialog_pemesan(null, closable);
        p.setVisible(true);

        t_idPemesan.setText(p.jb.getId_pemesan());
        t_unit.setText(p.jb.getUnit_pemesan());

        btn_barang.requestFocus();
        aktif();
    }//GEN-LAST:event_btn_pemesanActionPerformed

    private void btn_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_barangActionPerformed
        boolean closable = true;
        dialog_barang djb = new dialog_barang(null, closable);
        djb.setVisible(true);

        t_kodeBarang.setText(djb.jb.getKode_barang());
        t_namaBarang.setText(djb.jb.getNama_barang());

        t_jumlah.requestFocus();
        aktif();
    }//GEN-LAST:event_btn_barangActionPerformed

    private void tbl_sementaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sementaraMouseClicked
        int row = tbl_sementara.getSelectedRow();

        t_kodeBarang.setText(tbl_sementara.getModel().getValueAt(row, 0).toString());
        t_namaBarang.setText(tbl_sementara.getModel().getValueAt(row, 1).toString());
        t_jumlah.setText(tbl_sementara.getModel().getValueAt(row, 2).toString());
    }//GEN-LAST:event_tbl_sementaraMouseClicked

    private void tf_pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pencarianActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_barang;
    private rojerusan.RSMaterialButtonRectangle btn_batal;
    private rojerusan.RSMaterialButtonRectangle btn_batal1;
    private rojerusan.RSMaterialButtonRectangle btn_clear;
    private rojerusan.RSMaterialButtonRectangle btn_hapus;
    private rojerusan.RSMaterialButtonRectangle btn_hapussem;
    private javax.swing.JButton btn_pemesan;
    private rojerusan.RSMaterialButtonRectangle btn_perbaruisem;
    private rojerusan.RSMaterialButtonRectangle btn_print;
    private rojerusan.RSMaterialButtonRectangle btn_tambah;
    private rojerusan.RSMaterialButtonRectangle btn_tambah1;
    private rojerusan.RSMaterialButtonRectangle btn_tambahSem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JLabel lb_ID;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_dataUtama;
    private javax.swing.JPanel pn_detail;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin111;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin112;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin113;
    private javax.swing.JTextField t_idPemesan;
    private javax.swing.JTextField t_jumlah;
    private javax.swing.JTextField t_kodeBK;
    private javax.swing.JTextField t_kodeBarang;
    private javax.swing.JTextField t_namaBarang;
    private javax.swing.JTextField t_tgl;
    private javax.swing.JTextField t_unit;
    private javax.swing.JPanel tambahData;
    private javax.swing.JPanel tampilData;
    private tablecustom.tablez tbl_data;
    private tablecustom.tablez tbl_detail;
    private tablecustom.tablez tbl_sementara;
    private javax.swing.JTextField tf_pencarian;
    // End of variables declaration//GEN-END:variables

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new barang_keluar(lb_ID.getText()));
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void loadData() {
        btn_hapus.setVisible(false);
        btn_batal.setVisible(false);
        btn_print.setVisible(false);
        List<Model_BarangKeluar> list = servis.getData();
        tblMod.setData(list);
        if (btn_tambah.getText().equals("UBAH")) {
            btn_tambah.setText("TAMBAH");
        }
    }

    private void resetForm() {
        btn_tambah.requestFocus();
        btn_tambah.setText("TAMBAH");
        t_idPemesan.setText("");
        t_unit.setText("");
        t_kodeBarang.setText("");
        t_namaBarang.setText("");
        t_jumlah.setText("");
    }

    private void dataTabel() {
        tampilData.setVisible(false);
        tambahData.setVisible(true);

        int row = tbl_data.getSelectedRow();
        judul2.setText("Perbarui Pemesan");

        t_kodeBK.setText(tbl_data.getModel().getValueAt(row, 1).toString());
        t_tgl.setText(tbl_data.getModel().getValueAt(row, 2).toString());
        t_kodeBarang.setText(tbl_data.getModel().getValueAt(row, 3).toString());

        aktif();
        btn_tambah1.setText("PERBARUI");
        btn_clear.setText("BATAL");
        btn_batal1.setVisible(false);
        btn_batal.setVisible(true);
    }

    private void aktif() {
        t_jumlah.setEnabled(true);
    }

    private void hapusData() {
        int index = tbl_data.getSelectedRow();
        if (index != -1) {
            Model_BarangKeluar bk = tblMod.getData(tbl_data.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                servis.hapusData(bk);
                tblMod.hapusData(index);
                loadData();
                resetForm();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }

    private boolean validasiInput() {
        boolean valid = false;
        if (t_kodeBK.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode barang keluar tidak boleh kosong");
        } else if (t_tgl.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tanggal pemesan tidak boleh kosong");
        } else if (t_idPemesan.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID Pemesan tidak boleh kosong");
        } else {
            valid = true;
        }
        return valid;
    }

    private void simpanData() {
        if (validasiInput()) {
            String kode = t_kodeBK.getText();
            String idPem = t_idPemesan.getText();
            String unit = t_unit.getText();
            String idAdmin = lb_ID.getText();
            String tgl = t_tgl.getText();

            Model_BarangKeluar bk = new Model_BarangKeluar();
            Model_Pemesan p = new Model_Pemesan();
            Model_Admin a = new Model_Admin();

            bk.setKode_keluar(kode);
            p.setId_pemesan(idPem);
            p.setUnit_pemesan(unit);
            a.setId_admin(idAdmin);

            try {
                // Parse the string date to java.util.Date
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Replace "your_date_format" with the actual date format
                Date tglDate = sdf.parse(tgl);
                bk.setTgl_keluar(tglDate);
            } catch (ParseException e) {
                e.printStackTrace(); // Handle the parsing exception appropriately
                return; // Return or handle error accordingly
            }

            bk.setPemesanbarang(p);
            bk.setAdmin(a);

            servis.tambahData(bk);
            tblMod.tambahData(bk);
        }
    }

    private void simpanDet() {
        DefaultTableModel tb = (DefaultTableModel) tbl_sementara.getModel();
        int rowCount = tb.getRowCount();

        for (int i = 0; i < rowCount; i++) {
            Model_DetBarangKeluar d = new Model_DetBarangKeluar();
            Model_BarangKeluar s = new Model_BarangKeluar();
            Model_Barang mod = new Model_Barang();

            String kode = t_kodeBK.getText();
            String kodeBarang = tb.getValueAt(i, 0).toString();
            String namaBarang = tb.getValueAt(i, 1).toString();
            String jumlah = tb.getValueAt(i, 2).toString();

            s.setKode_keluar(kode);
            mod.setKode_barang(kodeBarang);
            mod.setNama_barang(namaBarang);
            d.setJml_keluar(Integer.parseInt(jumlah));

            d.setBarang(mod);
            d.setBarangkeluar(s);

            servis_det.tambahData(d);
        }

    }

    private void perbaruiData() {
        int index = tbl_data.getSelectedRow();
        if (index != -1) {
            Model_BarangKeluar mod = tblMod.getData(tbl_data.convertRowIndexToModel(index));

            if (validasiInput() == true) {
                String kode = t_kodeBK.getText();
                String idPem = t_idPemesan.getText();
                String unit = t_unit.getText();
                String idAdmin = lb_ID.getText();
                String tgl = t_tgl.getText();

                Model_BarangKeluar bk = new Model_BarangKeluar();
                Model_Pemesan p = new Model_Pemesan();
                Model_Admin a = new Model_Admin();

                bk.setKode_keluar(kode);
                p.setId_pemesan(idPem);
                p.setUnit_pemesan(unit);
                a.setId_admin(idAdmin);
                try {
                    // Parse the string date to java.util.Date
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Replace "your_date_format" with the actual date format
                    Date tglDate = sdf.parse(tgl);
                    bk.setTgl_keluar(tglDate);
                } catch (ParseException e) {
                    e.printStackTrace(); // Handle the parsing exception appropriately
                    return; // Return or handle error accordingly
                }

                bk.setPemesanbarang(p);
                bk.setAdmin(a);

                servis.tambahData(bk);
                tblMod.tambahData(bk);
            }
        }
    }

    private void perbaruiSementara() {

        int selectedRowIndex = tbl_sementara.getSelectedRow();

        if (selectedRowIndex != -1) {
            DefaultTableModel tb = (DefaultTableModel) tbl_sementara.getModel();

            tb.setValueAt(t_kodeBarang.getText(), selectedRowIndex, 0);
            tb.setValueAt(t_namaBarang.getText(), selectedRowIndex, 1);
            tb.setValueAt(t_jumlah.getText(), selectedRowIndex, 2);

            JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate!");
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan diupdate!");
        }

    }

    private void pencarian() {
        List<Model_BarangKeluar> list = servis.pencarian(tf_pencarian.getText().toLowerCase());
        tblMod.setData(list);
    }

    private void setTanggal() {
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd");
        t_tgl.setText(kal.format(sekarang));
    }

    private boolean cekStok(String kodeOnderdil, int jmh) {
        boolean stokCukup = false;
        PreparedStatement st = null;
        ResultSet rs = null;

        try {
            //query untuk mengambil data stok dari onderdil
            String sql = "SELECT stok FROM barang WHERE kode_barang = ?";
            st = conn.prepareStatement(sql);
            st.setString(1, kodeOnderdil);
            rs = st.executeQuery();

            if (rs.next()) {
                //ambil jumlah stok onderdil dari database
                int stok = rs.getInt("stok");

                if (stok >= jmh) {
                    stokCukup = true;
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            stokCukup = false;
        } finally {
            try {
                if (st != null) {
                    st.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        return stokCukup;
    }

}
