/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Model.Model_Barang;
import Model.Model_JenisBarang;
import TableMod.TableMod_Barang;
import dao.DAO_barang;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import service.Service_Barang;
import jnafilechooser.api.JnaFileChooser;

/**
 *
 * @author SyafiqUbai
 */
public class barang extends javax.swing.JPanel {

    private Service_Barang servis = new DAO_barang();
    TableMod_Barang tblMod = new TableMod_Barang();
    
    public barang() {
        initComponents();
        tbl_data.setModel(tblMod);

        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        scrollPaneWin111 = new scrollbarwin11.ScrollPaneWin11();
        tbl_data = new tablecustom.tablez();
        judul1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_tambah = new rojerusan.RSMaterialButtonRectangle();
        btn_hapus = new rojerusan.RSMaterialButtonRectangle();
        btn_batal = new rojerusan.RSMaterialButtonRectangle();
        tf_pencarian = new javax.swing.JTextField();
        btn_pencarian = new javax.swing.JLabel();
        btn_ekspor = new rojerusan.RSMaterialButtonRectangle();
        btn_impor = new rojerusan.RSMaterialButtonRectangle();
        tambahData = new javax.swing.JPanel();
        judul2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_tambah1 = new rojerusan.RSMaterialButtonRectangle();
        btn_clear = new rojerusan.RSMaterialButtonRectangle();
        btn_batal1 = new rojerusan.RSMaterialButtonRectangle();
        jPanel1 = new javax.swing.JPanel();
        tf_kode = new javax.swing.JTextField();
        lb_kode = new javax.swing.JLabel();
        lb_nama = new javax.swing.JLabel();
        tf_kodeJenis = new javax.swing.JTextField();
        lb_kode1 = new javax.swing.JLabel();
        tf_namJenis = new javax.swing.JTextField();
        lb_kode2 = new javax.swing.JLabel();
        tf_namBarang = new javax.swing.JTextField();
        lb_kode3 = new javax.swing.JLabel();
        tf_stok = new javax.swing.JTextField();
        btn_pilih = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        tampilData.setBackground(new java.awt.Color(255, 255, 255));

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dataMouseClicked(evt);
            }
        });
        scrollPaneWin111.setViewportView(tbl_data);

        judul1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        judul1.setText("Data Barang");

        btn_tambah.setBackground(new java.awt.Color(0, 0, 255));
        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(153, 0, 0));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(0, 102, 0));
        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        tf_pencarian.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        tf_pencarian.setText("Search");
        tf_pencarian.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_pencarian.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_pencarianFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_pencarianFocusLost(evt);
            }
        });
        tf_pencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_pencarianKeyPressed(evt);
            }
        });

        btn_pencarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search (1).png"))); // NOI18N

        btn_ekspor.setBackground(new java.awt.Color(204, 204, 0));
        btn_ekspor.setText("EKSPOR");
        btn_ekspor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eksporActionPerformed(evt);
            }
        });

        btn_impor.setBackground(new java.awt.Color(0, 51, 51));
        btn_impor.setText("IMPOR");
        btn_impor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imporActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ekspor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_impor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_pencarian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 679, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btn_pencarian))
                    .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_ekspor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_impor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(tampilData, "card2");

        tambahData.setBackground(new java.awt.Color(255, 255, 255));

        judul2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        judul2.setText("Tambah Data Barang");

        btn_tambah1.setBackground(new java.awt.Color(0, 0, 255));
        btn_tambah1.setText("TAMBAH");
        btn_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah1ActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(153, 0, 0));
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_batal1.setBackground(new java.awt.Color(0, 102, 0));
        btn_batal1.setText("BATAL");
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tf_kode.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N

        lb_kode.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lb_kode.setText("Kode Barang");

        lb_nama.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lb_nama.setText("Kode Jenis");

        tf_kodeJenis.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N

        lb_kode1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lb_kode1.setText("Nama Jenis");

        tf_namJenis.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N

        lb_kode2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lb_kode2.setText("Nama Barang");

        tf_namBarang.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N

        lb_kode3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lb_kode3.setText("Stok");

        tf_stok.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        tf_stok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_stokKeyTyped(evt);
            }
        });

        btn_pilih.setText("Pilih");
        btn_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_stok)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb_kode3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_kode)
                            .addComponent(tf_namJenis)
                            .addComponent(tf_namBarang)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_kode1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_kode2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tf_kodeJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_pilih)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lb_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_pilih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_kodeJenis, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lb_kode1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_namJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_kode2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_namBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_kode3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahDataLayout = new javax.swing.GroupLayout(tambahData);
        tambahData.setLayout(tambahDataLayout);
        tambahDataLayout.setHorizontalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahDataLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tambahDataLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tambahDataLayout.setVerticalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(tambahData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        String x = btn_tambah.getText();
        int row = tbl_data.getSelectedRow();
        tf_kode.setEnabled(false);
        tf_kodeJenis.setEnabled(false);
        tf_namJenis.setEnabled(false);
        if (x.equals("TAMBAH")) {
            
            mainPanel.removeAll();
            mainPanel.repaint();
            mainPanel.revalidate();

            mainPanel.add(tambahData);
            mainPanel.repaint();
            mainPanel.revalidate();
            
            judul2.setText("Tambah Data Barang");
            btn_tambah1.setText("SIMPAN");
            tf_kode.setEnabled(false);
            tf_kode.setText(servis.nomor());
            loadData();
        } else {
            int index = tbl_data.getSelectedRow();
            if (index != -1) {
                Model_Barang mod = tblMod.getData(tbl_data.convertRowIndexToModel(index));

                if (x.equals("UBAH")) {
                    dataTabel();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan diubah");
            }
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        String x = btn_clear.getText();
        if (x.equals("CLEAR")) {
            lb_nama.setText("");
        } else {
            tampilPanel();
            loadData();
            resetForm();
        }
        btn_clear.setText("CLEAR");
        btn_batal1.setVisible(true);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah1ActionPerformed
        if (btn_tambah1.getText().equals("TAMBAH")) {
            btn_tambah1.setText("SIMPAN");
            tf_kode.setText(servis.nomor());
        } else if (btn_tambah1.getText().equals("SIMPAN")) {
            simpanData();
        } else if (btn_tambah1.getText().equals("PERBARUI")) {
            perbaruiData();

        }
        loadData();
    }//GEN-LAST:event_btn_tambah1ActionPerformed

    private void tbl_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseClicked
        if (btn_tambah.getText().equals("TAMBAH")) {
            btn_tambah.setText("UBAH");
        }
        btn_hapus.setVisible(true);
        btn_batal.setVisible(true);
        btn_ekspor.setVisible(true);
    }//GEN-LAST:event_tbl_dataMouseClicked

    private void tf_pencarianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pencarianKeyPressed
       pencarian();
    }//GEN-LAST:event_tf_pencarianKeyPressed

    private void tf_pencarianFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_pencarianFocusGained
        String username = tf_pencarian.getText();
        if (username.equals("Search")) {
            tf_pencarian.setText("");
        }
    }//GEN-LAST:event_tf_pencarianFocusGained

    private void tf_pencarianFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_pencarianFocusLost
        String user = tf_pencarian.getText();
        if (user.equalsIgnoreCase("Search") || user.equalsIgnoreCase("")) {
            tf_pencarian.setText("Search");
        }
    }//GEN-LAST:event_tf_pencarianFocusLost

    private void btn_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihActionPerformed
        boolean closable = true;
        dialog_jenisBarang djb = new dialog_jenisBarang(null, closable);
        djb.setVisible(true);
        
        tf_kodeJenis.setText(djb.jb.getKode_jenis());
        tf_namJenis.setText(djb.jb.getNama_jenis());
        
        tf_namBarang.requestFocus();
        aktif();
    }//GEN-LAST:event_btn_pilihActionPerformed

    private void btn_eksporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eksporActionPerformed
        JnaFileChooser fileChooser = new JnaFileChooser();
        Window window = null;
        boolean action = fileChooser.showSaveDialog(window);

        if (action) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath() + ".xlsx";
            TableMod_Barang model = (TableMod_Barang) tbl_data.getModel();
            List<Model_Barang> exportedData = servis.getData();
            servis.exportToExcel(exportedData, filePath);
        }
        loadData();
    }//GEN-LAST:event_btn_eksporActionPerformed

    private void tf_stokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_stokKeyTyped
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Masukan hanya bilangan angka !");

            evt.consume();
        }
    }//GEN-LAST:event_tf_stokKeyTyped

    private void btn_imporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imporActionPerformed
        JnaFileChooser fileChooser = new JnaFileChooser();
        Window window = null;
        boolean action = fileChooser.showOpenDialog(window);

        if (action) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            List<Model_Barang> importedData = new ArrayList<>();
            servis.importFromExcel(importedData, filePath);
            tblMod.setData(importedData);
        }
        loadData();
    }//GEN-LAST:event_btn_imporActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_batal;
    private rojerusan.RSMaterialButtonRectangle btn_batal1;
    private rojerusan.RSMaterialButtonRectangle btn_clear;
    private rojerusan.RSMaterialButtonRectangle btn_ekspor;
    private rojerusan.RSMaterialButtonRectangle btn_hapus;
    private rojerusan.RSMaterialButtonRectangle btn_impor;
    private javax.swing.JLabel btn_pencarian;
    private javax.swing.JButton btn_pilih;
    private rojerusan.RSMaterialButtonRectangle btn_tambah;
    private rojerusan.RSMaterialButtonRectangle btn_tambah1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel lb_kode;
    private javax.swing.JLabel lb_kode1;
    private javax.swing.JLabel lb_kode2;
    private javax.swing.JLabel lb_kode3;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JPanel mainPanel;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin111;
    private javax.swing.JPanel tambahData;
    private javax.swing.JPanel tampilData;
    private tablecustom.tablez tbl_data;
    private javax.swing.JTextField tf_kode;
    private javax.swing.JTextField tf_kodeJenis;
    private javax.swing.JTextField tf_namBarang;
    private javax.swing.JTextField tf_namJenis;
    private javax.swing.JTextField tf_pencarian;
    private javax.swing.JTextField tf_stok;
    // End of variables declaration//GEN-END:variables

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new barang());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void loadData() {
        btn_hapus.setVisible(false);
        btn_batal.setVisible(false);
        List<Model_Barang> list = servis.getData();
        tblMod.setData(list);
        if (btn_tambah.getText().equals("UBAH")) {
            btn_tambah.setText("TAMBAH");
        }
    }

    private void resetForm() {
        btn_tambah.requestFocus();
        btn_tambah.setText("TAMBAH");
        tf_kode.setText("");
        tf_kodeJenis.setText("");
        tf_namJenis.setText("");
        tf_namBarang.setText("");
        tf_stok.setText("");
        
    }

    private void dataTabel() {
        tampilData.setVisible(false);
        tambahData.setVisible(true);
        
        int row = tbl_data.getSelectedRow();
        judul2.setText("Perbarui Data Barang");
        
        tf_kode.setEnabled(false);
        tf_kodeJenis.setEnabled(false);
        tf_namJenis.setEnabled(false);
        
        tf_kode.setText(tbl_data.getModel().getValueAt(row, 1).toString());
        tf_kodeJenis.setText(tbl_data.getModel().getValueAt(row, 2).toString());
        tf_namJenis.setText(tbl_data.getModel().getValueAt(row, 3).toString());
        tf_namBarang.setText(tbl_data.getModel().getValueAt(row, 4).toString());
        tf_stok.setText(tbl_data.getModel().getValueAt(row, 5).toString());
        
        aktif();
        btn_tambah1.setText("PERBARUI");
        btn_clear.setText("BATAL");
        btn_batal1.setVisible(false);
        btn_batal.setVisible(true);
    }
    
    private void aktif() {
        tf_namBarang.setEnabled(true);
        tf_stok.setEnabled(true);
    }

    private void hapusData() {
        int index = tbl_data.getSelectedRow();
        if(index!=-1){
            Model_Barang brg = tblMod.getData(tbl_data.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                servis.hapusData(brg);
                tblMod.hapusData(index);
                loadData();
                resetForm();  
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }
    
     private boolean validasiInput() {
        boolean valid = false;
        if (tf_kode.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Barang tidak boleh kosong");
        } else if (tf_kodeJenis.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Jenis tidak boleh kosong");
        } else if (tf_namJenis.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Jenis tidak boleh kosong");
        } else if (tf_namBarang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Barang tidak boleh kosong");
        } else if (tf_stok.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Stok tidak boleh kosong");
        } else {
            valid = true;
        }
        return valid;
    }
     
    private void simpanData() {
        if(validasiInput()==true){
            String kode = tf_kode.getText();
            String kode_jenis = tf_kodeJenis.getText();
            String nama_jenis = tf_namJenis.getText();
            String nama_barang = tf_namBarang.getText();
            int stok = Integer.parseInt(tf_stok.getText());
            
            Model_Barang b = new Model_Barang();
            Model_JenisBarang jb = new Model_JenisBarang();
            
            b.setKode_barang(kode);
            jb.setKode_jenis(kode_jenis);
            jb.setNama_jenis(nama_jenis);
            b.setNama_barang(nama_barang);
            b.setStok(stok);
            
            b.setJenisbarang(jb);
              
            servis.tambahData(b);
            tblMod.tambahData(b);
            loadData();
            resetForm();
            tampilPanel();
            btn_tambah1.setText("TAMBAH");
        }
    }

    private void perbaruiData() {
        int index = tbl_data.getSelectedRow();
        if (index != -1) {
            Model_Barang mod = tblMod.getData(tbl_data.convertRowIndexToModel(index));

            if (validasiInput() == true) {
                String kode = tf_kode.getText();
                String kode_jenis = tf_kodeJenis.getText();
                String nama_jenis = tf_namJenis.getText();
                String nama_barang = tf_namBarang.getText();
                int stok = Integer.parseInt(tf_stok.getText());

                Model_Barang b = new Model_Barang();
                Model_JenisBarang jb = new Model_JenisBarang();

                b.setKode_barang(kode);
                jb.setKode_jenis(kode_jenis);
                jb.setNama_jenis(nama_jenis);
                b.setNama_barang(nama_barang);
                b.setStok(stok);

                b.setJenisbarang(jb);
                servis.perbaruiData(b);
                tblMod.perbaruiData(index, b);
                loadData();
                resetForm();
                tampilPanel();

            }
        }
    }
    
    private void pencarian() {
       List<Model_Barang> list = servis.pencarian(tf_pencarian.getText().toLowerCase());
        tblMod.setData(list);
    }
  
}
