/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Model.Model_BarangMasuk;
import Model.Model_DetBarangMasuk;
import Model.Model_pesananSupply;
import TableMod.TableMod_pesananSupply;
import dao.DAO_BarangMasuk;
import dao.DAO_detBarangMasuk;
import dao.DAO_pesanansuplay;
import service.Service_BarangMasuk;
import service.Service_DetBarangMasuk;
import service.Service_Pesanan;
import tabelModel.TableMod_BarangMasuk;
import tabelModel.TableMod_DetBarangMasuk;
import Model.Model_Admin;
import Model.Model_Barang;
import config.koneksi;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author SyafiqUbai
 */
public class barang_masuk extends javax.swing.JPanel {

    private Service_BarangMasuk servis = new DAO_BarangMasuk();
    private TableMod_BarangMasuk tblMod = new TableMod_BarangMasuk();

    private Service_Pesanan servis_psn = new DAO_pesanansuplay();
    private TableMod_pesananSupply tblModel_psn = new TableMod_pesananSupply();

    private Service_DetBarangMasuk servis_detpsn = new DAO_detBarangMasuk();
    private TableMod_DetBarangMasuk tblModel_det = new TableMod_DetBarangMasuk();
    private TableMod_DetBarangMasuk tblModel_det2 = new TableMod_DetBarangMasuk();

    public barang_masuk(String id) {
        initComponents();
        tbl_data.setModel(tblMod);
        tbl_detail.setModel(tblModel_det);
        tbl_detail2.setModel(tblModel_det2);
//        btn_search.requestFocus();

        loadData();
        pn_detail.setVisible(false);
        lb_id.setText(id);
        lb_id.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNIssNG: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        scrollPaneWin111 = new scrollbarwin11.ScrollPaneWin11();
        tbl_data = new tablecustom.tablez();
        judul1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_tambah = new rojerusan.RSMaterialButtonRectangle();
        btn_hapus = new rojerusan.RSMaterialButtonRectangle();
        btn_batal = new rojerusan.RSMaterialButtonRectangle();
        tf_pencarian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_print = new rojerusan.RSMaterialButtonRectangle();
        pn_detail = new javax.swing.JPanel();
        scrollPaneWin112 = new scrollbarwin11.ScrollPaneWin11();
        tbl_detail = new tablecustom.tablez();
        judul3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tambahData = new javax.swing.JPanel();
        judul2 = new javax.swing.JLabel();
        lb_total = new javax.swing.JSeparator();
        btn_tambah1 = new rojerusan.RSMaterialButtonRectangle();
        btn_clear = new rojerusan.RSMaterialButtonRectangle();
        btn_batal1 = new rojerusan.RSMaterialButtonRectangle();
        pn_dataUtama = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        t_kodeMasuk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_tgl = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        t_idpesanan = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        t_status = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        t_namasupplier = new javax.swing.JTextField();
        scrollPaneWin113 = new scrollbarwin11.ScrollPaneWin11();
        tbl_detail2 = new tablecustom.tablez();
        lb_id = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        tampilData.setBackground(new java.awt.Color(255, 255, 255));

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dataMouseClicked(evt);
            }
        });
        scrollPaneWin111.setViewportView(tbl_data);

        judul1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        judul1.setText("Data Barang Masuk");

        btn_tambah.setBackground(new java.awt.Color(0, 0, 255));
        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(153, 0, 0));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(0, 102, 0));
        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        tf_pencarian.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        tf_pencarian.setText("Search");
        tf_pencarian.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_pencarian.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_pencarianFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_pencarianFocusLost(evt);
            }
        });
        tf_pencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_pencarianKeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search (1).png"))); // NOI18N

        btn_print.setBackground(new java.awt.Color(204, 204, 0));
        btn_print.setText("print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        pn_detail.setBackground(new java.awt.Color(255, 255, 255));

        tbl_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneWin112.setViewportView(tbl_detail);

        judul3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        judul3.setText("Detail Data Pesanan");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_detailLayout = new javax.swing.GroupLayout(pn_detail);
        pn_detail.setLayout(pn_detailLayout);
        pn_detailLayout.setHorizontalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneWin112, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(judul3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pn_detailLayout.setVerticalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_detailLayout.createSequentialGroup()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(judul3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPaneWin112, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tampilDataLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tampilDataLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(pn_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        mainPanel.add(tampilData, "card2");

        tambahData.setBackground(new java.awt.Color(255, 255, 255));

        judul2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        judul2.setText("Tambah Pemesan");

        btn_tambah1.setBackground(new java.awt.Color(0, 0, 255));
        btn_tambah1.setText("TAMBAH");
        btn_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah1ActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(153, 0, 0));
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_batal1.setBackground(new java.awt.Color(0, 102, 0));
        btn_batal1.setText("BATAL");
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        pn_dataUtama.setBackground(new java.awt.Color(0, 153, 102));
        pn_dataUtama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kode Barang Masuk");

        t_kodeMasuk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal Barang Masuk");

        t_tgl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout pn_dataUtamaLayout = new javax.swing.GroupLayout(pn_dataUtama);
        pn_dataUtama.setLayout(pn_dataUtamaLayout);
        pn_dataUtamaLayout.setHorizontalGroup(
            pn_dataUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dataUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_dataUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_kodeMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_dataUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        pn_dataUtamaLayout.setVerticalGroup(
            pn_dataUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dataUtamaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pn_dataUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_dataUtamaLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_dataUtamaLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_kodeMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBackground(new java.awt.Color(0, 153, 102));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Supply");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        t_idpesanan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Konfirmasi Pesanan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Status");

        t_status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Id Pesanan");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nama Supplier");

        t_namasupplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_status, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_idpesanan, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_namasupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(t_idpesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(t_namasupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(14, 14, 14))))
        );

        tbl_detail2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneWin113.setViewportView(tbl_detail2);

        lb_id.setText("AD12001   ");

        javax.swing.GroupLayout tambahDataLayout = new javax.swing.GroupLayout(tambahData);
        tambahData.setLayout(tambahDataLayout);
        tambahDataLayout.setHorizontalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahDataLayout.createSequentialGroup()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahDataLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahDataLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pn_dataUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                .addComponent(lb_id)
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahDataLayout.createSequentialGroup()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPaneWin113, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_total))
                .addGap(10, 10, 10))
        );
        tambahDataLayout.setVerticalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_dataUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneWin113, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(tambahData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
//        String x = btn_tambah.getText();
//        int row = tbl_data.getSelectedRow();
//        tf_kode.setEnabled(false);
//        if (x.equals("TAMBAH")) {

        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahData);
        mainPanel.repaint();
        mainPanel.revalidate();
        setTanggal();

        btn_tambah1.setText("SIMPAN");
//        btn_jenisbarang.setEnabled(true);
        t_kodeMasuk.setText(servis.nomor());
        setTanggal();
        loadData();

//            
//            judul2.setText("Tambah Pemesan");
//            btn_tambah1.setText("SIMPAN");
//            tf_kode.setEnabled(false);
//            tf_kode.setText(servis.nomor());
//            loadData();
//        } else {
//            int index = tbl_data.getSelectedRow();
//            if (index != -1) {
//                Model_Pemesan mod = tblMod.getData(tbl_data.convertRowIndexToModel(index));
//
//                if (x.equals("UBAH")) {
//                    dataTabel();
//                }
//            } else {
//                JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan diubah");
//            }
//        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        String x = btn_clear.getText();
        if (x.equals("CLEAR")) {
            t_kodeMasuk.setText("");
        } else {
            tampilPanel();
            loadData();
            resetForm();
        }
        btn_clear.setText("CLEAR");
        btn_batal1.setVisible(true);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah1ActionPerformed
        if (btn_tambah1.getText().equals("TAMBAH")) {
            btn_tambah1.setText("SIMPAN");
        } else if (btn_tambah1.getText().equals("SIMPAN")) {
            simpanData();
            loadData();
            resetForm();
            tampilPanel();
            btn_tambah1.setText("TAMBAH");
        } else if (btn_tambah1.getText().equals("PERBARUI")) {
//            perbaruiData();
        }

    }//GEN-LAST:event_btn_tambah1ActionPerformed

    private void tf_pencarianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pencarianKeyPressed
        pencarian();
    }//GEN-LAST:event_tf_pencarianKeyPressed

    private void tf_pencarianFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_pencarianFocusGained
        String username = tf_pencarian.getText();
        if (username.equals("Search")) {
            tf_pencarian.setText("");
        }
    }//GEN-LAST:event_tf_pencarianFocusGained

    private void tf_pencarianFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_pencarianFocusLost
        String user = tf_pencarian.getText();
        if (user.equalsIgnoreCase("Search") || user.equalsIgnoreCase("")) {
            tf_pencarian.setText("Search");
        }
    }//GEN-LAST:event_tf_pencarianFocusLost

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
         {
//            String path = "src/report/laporanMasuk.jrxml";
//            JasperReport jasperReport = null;
//            SimpleDateFormat tgl = new SimpleDateFormat("dd-MM-yyyy");
//
//            jasperReport = JasperCompileManager.compileReport(path);
//
//            HashMap<String, Object> par = new HashMap<>();
//            par.put("tglAwal", jDateChooser1.getDate());
//            par.put("tglAkhir", jDateChooser2.getDate());
//            JasperPrint print = JasperFillManager.fillReport(jasperReport, par, koneksi.getConnection());
//            JasperViewer viewer = new JasperViewer(print, false);
//            viewer.setVisible(true);
//        } catch (JRException ex) {
//            Logger.getLogger(barang_masuk.class.getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_btn_printActionPerformed

    private void tbl_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseClicked
        int row = tbl_data.getSelectedRow();
        String id = tbl_data.getValueAt(row, 1).toString();

        pn_detail.setVisible(true);
        List<Model_DetBarangMasuk> list = servis_detpsn.getByid(id);
        tblModel_det.setData(list);
    }//GEN-LAST:event_tbl_dataMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean closable = true;
        dialog_pesanan dk = new dialog_pesanan(null, closable);
        dk.setVisible(true);

        t_idpesanan.setText(dk.jb.getId_pesanan());
        t_status.setText(dk.jb.getStatus());
        t_namasupplier.setText(dk.jb.getSupplier().getNama_supplier());
        detail();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        bayar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        pn_detail.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_batal;
    private rojerusan.RSMaterialButtonRectangle btn_batal1;
    private rojerusan.RSMaterialButtonRectangle btn_clear;
    private rojerusan.RSMaterialButtonRectangle btn_hapus;
    private rojerusan.RSMaterialButtonRectangle btn_print;
    private rojerusan.RSMaterialButtonRectangle btn_tambah;
    private rojerusan.RSMaterialButtonRectangle btn_tambah1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JLabel lb_id;
    private javax.swing.JSeparator lb_total;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_dataUtama;
    private javax.swing.JPanel pn_detail;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin111;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin112;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin113;
    private javax.swing.JTextField t_idpesanan;
    private javax.swing.JTextField t_kodeMasuk;
    private javax.swing.JTextField t_namasupplier;
    private javax.swing.JTextField t_status;
    private javax.swing.JTextField t_tgl;
    private javax.swing.JPanel tambahData;
    private javax.swing.JPanel tampilData;
    private tablecustom.tablez tbl_data;
    private tablecustom.tablez tbl_detail;
    private tablecustom.tablez tbl_detail2;
    private javax.swing.JTextField tf_pencarian;
    // End of variables declaration//GEN-END:variables

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new barang_masuk(lb_id.getText()));
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void loadData() {
        btn_hapus.setVisible(false);
        btn_batal.setVisible(false);
        btn_print.setVisible(false);
        List<Model_BarangMasuk> list = servis.getData();
        tblMod.setData(list);
        if (btn_tambah.getText().equals("UBAH")) {
            btn_tambah.setText("TAMBAH");
        }
    }

    private void resetForm() {
        btn_tambah.requestFocus();
        btn_tambah.setText("TAMBAH");
        t_kodeMasuk.setText("");
        t_tgl.setText("");
        t_namasupplier.setText("");
        t_idpesanan.setText("");

    }

    private void dataTabel() {
        tampilData.setVisible(false);
        tambahData.setVisible(true);

        int row = tbl_data.getSelectedRow();
        judul2.setText("Perbarui Pemesan");

        aktif();
        btn_tambah1.setText("PERBARUI");
        btn_clear.setText("BATAL");
        btn_batal1.setVisible(false);
        btn_batal.setVisible(true);
    }

    private void aktif() {
        t_kodeMasuk.setEnabled(true);
    }

    private void hapusData() {
        int index = tbl_data.getSelectedRow();
        if (index != -1) {
            Model_pesananSupply brg = tblModel_psn.getData(tbl_data.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                servis_psn.hapusData(brg);
                tblModel_psn.hapusData(index);
                loadData();
                resetForm();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }

    private boolean validasiInput() {
        boolean valid = false;
        if (t_kodeMasuk.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Id Pesanan tidak boleh kosong");
        } else if (t_idpesanan.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Id Suppplier tidak boleh kosong");
//    }else if (t_kodebarang.getText().trim().isEmpty()){
//         JOptionPane.showMessageDialog(null, "Kode Barang boleh kosong"); 
        } else {
            valid = true;
        }
        return valid;
    }

    private void simpanData() {
        if (validasiInput()) {
            String kode = t_kodeMasuk.getText();
            String idPem = t_idpesanan.getText();
            String idAdmin = lb_id.getText();
            String tgl = t_tgl.getText();

            Model_BarangMasuk bk = new Model_BarangMasuk();
            Model_pesananSupply p = new Model_pesananSupply();
            Model_Admin a = new Model_Admin();

            bk.setKode_masuk(kode);
            p.setId_pesanan(idPem);
            a.setId_admin(idAdmin);

            try {
                // Parse the string date to java.util.Date
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Replace "your_date_format" with the actual date format
                Date tglDate = sdf.parse(tgl);
                bk.setTgl_masuk(tglDate);
            } catch (ParseException e) {
                e.printStackTrace(); // Handle the parsing exception appropriately
                return; // Return or handle error accordingly
            }

            bk.setPesanan(p);
            bk.setAdmin(a);

            servis.tambahData(bk);
            tblMod.tambahData(bk);
        }
    }

    private void perbaruiData() {
//        int index = tbl_data.getSelectedRow();
//        if (index != -1) {
//            Model_pesananSupply mod = tblModel_psn.getData(tbl_data.convertRowIndexToModel(index));
//
//            if (validasiInput() == true) {
//                String kode = tf_kode.getText();
//                String nama = tf_nama.getText();
//                String unit = tf_unit.getText();
//
//                Model_Pemesan modi = new Model_Pemesan();
//
//                modi.setId_pemesan(kode);
//                modi.setNama_pemesan(nama);
//                modi.setUnit_pemesan(unit);
//
//                servis_psn.perbaruiData(mod);
//                tblModel_psn.perbaruiData(index, mod);
//                loadData();
//                resetForm();
//                tampilPanel();
//
//            }
//        }
    }

    private void pencarian() {
        List<Model_pesananSupply> list = servis_psn.pencarian(tf_pencarian.getText().toLowerCase());
        tblModel_psn.setData(list);
    }

    private boolean validasiIn() {
        boolean valid = false;
        if (t_kodeMasuk.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Supply Barang tidak boleh kosong");
        } else if (t_tgl.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tgl Supply tidak boleh kosong");
//        } else if (t_kodebarang.getText().trim().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Harus Ada Barang Yang di Pesan");
//        } else if (t_idadmin.getText().trim().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "ID Admin tidak boleh kosong");

        } else {
            valid = true;
        }
        return valid;
    }

    private void simpatDet() {
        if (validasiInput() == true) {
            DefaultTableModel tb = (DefaultTableModel) tbl_detail2.getModel();
            int rowCount = tb.getRowCount();

            for (int i = 0; i < rowCount; i++) {
                Model_DetBarangMasuk d = new Model_DetBarangMasuk();
                Model_pesananSupply s = new Model_pesananSupply();
                Model_Barang mod = new Model_Barang();

                String kode = t_kodeMasuk.getText();
                String kodeBarang = tb.getValueAt(i, 0).toString();
                String namaBarang = tb.getValueAt(i, 1).toString();
                String jumlah = tb.getValueAt(i, 2).toString();

                s.setId_pesanan(kode);
                mod.setKode_barang(kodeBarang);
                mod.setNama_barang(namaBarang);
                d.setJml_masuk(Integer.parseInt(jumlah));

                d.setBarang(mod);
                d.setPesanan(s);

                servis_detpsn.tambahData(d);
            }
        }

    }

    private void perbaruiSementara() {
//        int selectedRowIndex = tbl_detail2.getSelectedRow();
//
//        if (selectedRowIndex != -1) {
//            DefaultTableModel tb = (DefaultTableModel) tbl_detail2.getModel();
//            
//            tb.setValueAt(t_kodebarang.getText(), selectedRowIndex, 0);
//            tb.setValueAt(t_namabarang.getText(), selectedRowIndex, 1);
//            
//            tb.setValueAt(t_jumlah.getText(), selectedRowIndex, 2);
//            
//
//            JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate!");
//        } else {
//            JOptionPane.showMessageDialog(this, "Pilih baris yang akan diupdate!");
//        }

    }

    private void setTanggal() {
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd");
        t_tgl.setText(kal.format(sekarang));
    }

    private void bayar() {
        if (!t_kodeMasuk.getText().trim().isEmpty()) {
            if (JOptionPane.showConfirmDialog(null, "Yakin Akan Melakukan Konfirmasi Barang?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                String nom = t_idpesanan.getText();
                Model_pesananSupply sp = new Model_pesananSupply();

                sp.setId_pesanan(nom);
                sp.setStatus("Sukses");
                servis_psn.ubahData(sp);
                t_status.setText("Sukses");

            } else {
                JOptionPane.showMessageDialog(null, "Masukkan Kode Supply yang di konfirmasi!!!");
            }
        }
    }

    private void detail() {
        String id = t_idpesanan.getText();

        List<Model_DetBarangMasuk> list = servis_detpsn.getByid(id);
        tblModel_det2.setData(list);

    }
}
