/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.Timer;
import view.Laporan_keluar;
import view.Laporan_masuk;
import view.admin;
import view.barang;
import view.jenis_barang;
import view.pemesan;
import view.barang_keluar;
import view.barang_masuk;
import view.pesananSupply;
import view.supplier;

/**
 *
 * @author SyafiqUbai
 */
public class menu_utama extends javax.swing.JFrame {

    /**
     * Creates new form menu_utama
     */
    private Timer timer;
    
    public menu_utama(String Id, String Nama, String User) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        timer = new Timer(1000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showDayDateTime();
            }
        });
        
        timer.start();
        lb_user.setText(Nama);
        lb_id.setText(Id);
        lb_id.setVisible(false);
    }
    
    private void showDayDateTime() {
        Calendar calender = Calendar.getInstance();
        Date now = new Date();
        SimpleDateFormat formatHari = new SimpleDateFormat("EEEE", new Locale("in","ID"));
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        String hari = formatHari.format(calender.getTime());
        String dateTime = dateFormat.format(now);
        time.setText(hari+", "+dateTime);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        navbar = new jpanelgradient.JPanelGradient();
        time = new javax.swing.JLabel();
        lb_user = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        scrollPaneWin111 = new scrollbarwin11.ScrollPaneWin11();
        scroll = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        mn = new javax.swing.JPanel();
        ln = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_jenis = new javax.swing.JLabel();
        mn1 = new javax.swing.JPanel();
        ln1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_admin = new javax.swing.JLabel();
        mn2 = new javax.swing.JPanel();
        ln2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_supplier = new javax.swing.JLabel();
        mn3 = new javax.swing.JPanel();
        ln3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_pemesan = new javax.swing.JLabel();
        mn4 = new javax.swing.JPanel();
        ln4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_barang = new javax.swing.JLabel();
        mn5 = new javax.swing.JPanel();
        ln5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JLabel();
        mn6 = new javax.swing.JPanel();
        ln6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_BM = new javax.swing.JLabel();
        mn7 = new javax.swing.JPanel();
        ln7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_pemesanan = new javax.swing.JLabel();
        mn9 = new javax.swing.JPanel();
        ln9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        mn10 = new javax.swing.JPanel();
        ln10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btn_BK = new javax.swing.JLabel();
        mn13 = new javax.swing.JPanel();
        ln13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btn_LaporanMasuk = new javax.swing.JLabel();
        mn14 = new javax.swing.JPanel();
        ln14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btn_LaporanKeluar = new javax.swing.JLabel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel.setLayout(new java.awt.BorderLayout());

        navbar.setBackground(new java.awt.Color(255, 255, 255));
        navbar.setColorStart(new java.awt.Color(0, 102, 51));

        time.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time.setText("Tanggal & Waktu");

        lb_user.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lb_user.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_user.setText("Nama");

        lb_id.setText("ID");

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarLayout.createSequentialGroup()
                .addContainerGap(703, Short.MAX_VALUE)
                .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(lb_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panel.add(navbar, java.awt.BorderLayout.PAGE_START);

        scroll.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("HOME");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("MASTER DATA");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("TRANSAKSI");

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("LAINYA");

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("LAPORAN");

        mn.setBackground(new java.awt.Color(255, 255, 255));

        ln.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout lnLayout = new javax.swing.GroupLayout(ln);
        ln.setLayout(lnLayout);
        lnLayout.setHorizontalGroup(
            lnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        lnLayout.setVerticalGroup(
            lnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/postal.png"))); // NOI18N

        btn_jenis.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_jenis.setForeground(new java.awt.Color(153, 153, 153));
        btn_jenis.setText("Jenis Barang");
        btn_jenis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_jenisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_jenisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_jenisMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mnLayout = new javax.swing.GroupLayout(mn);
        mn.setLayout(mnLayout);
        mnLayout.setHorizontalGroup(
            mnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mnLayout.setVerticalGroup(
            mnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnLayout.createSequentialGroup()
                .addGroup(mnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mnLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(btn_jenis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        mn1.setBackground(new java.awt.Color(255, 255, 255));

        ln1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ln1Layout = new javax.swing.GroupLayout(ln1);
        ln1.setLayout(ln1Layout);
        ln1Layout.setHorizontalGroup(
            ln1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ln1Layout.setVerticalGroup(
            ln1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user (1).png"))); // NOI18N

        btn_admin.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_admin.setForeground(new java.awt.Color(153, 153, 153));
        btn_admin.setText("Admin");
        btn_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_adminMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mn1Layout = new javax.swing.GroupLayout(mn1);
        mn1.setLayout(mn1Layout);
        mn1Layout.setHorizontalGroup(
            mn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ln1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        mn1Layout.setVerticalGroup(
            mn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn1Layout.createSequentialGroup()
                .addComponent(ln1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mn1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mn1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mn2.setBackground(new java.awt.Color(255, 255, 255));

        ln2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ln2Layout = new javax.swing.GroupLayout(ln2);
        ln2.setLayout(ln2Layout);
        ln2Layout.setHorizontalGroup(
            ln2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ln2Layout.setVerticalGroup(
            ln2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parcel (2).png"))); // NOI18N

        btn_supplier.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_supplier.setForeground(new java.awt.Color(153, 153, 153));
        btn_supplier.setText("Supplier");
        btn_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_supplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_supplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_supplierMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mn2Layout = new javax.swing.GroupLayout(mn2);
        mn2.setLayout(mn2Layout);
        mn2Layout.setHorizontalGroup(
            mn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ln2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        mn2Layout.setVerticalGroup(
            mn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn2Layout.createSequentialGroup()
                .addComponent(ln2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mn2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mn2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mn3.setBackground(new java.awt.Color(255, 255, 255));

        ln3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ln3Layout = new javax.swing.GroupLayout(ln3);
        ln3.setLayout(ln3Layout);
        ln3Layout.setHorizontalGroup(
            ln3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ln3Layout.setVerticalGroup(
            ln3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customer.png"))); // NOI18N

        btn_pemesan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_pemesan.setForeground(new java.awt.Color(153, 153, 153));
        btn_pemesan.setText("Pemesan");
        btn_pemesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pemesanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pemesanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pemesanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mn3Layout = new javax.swing.GroupLayout(mn3);
        mn3.setLayout(mn3Layout);
        mn3Layout.setHorizontalGroup(
            mn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ln3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        mn3Layout.setVerticalGroup(
            mn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn3Layout.createSequentialGroup()
                .addComponent(ln3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mn3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mn3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_pemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mn4.setBackground(new java.awt.Color(255, 255, 255));

        ln4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ln4Layout = new javax.swing.GroupLayout(ln4);
        ln4.setLayout(ln4Layout);
        ln4Layout.setHorizontalGroup(
            ln4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ln4Layout.setVerticalGroup(
            ln4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/goods.png"))); // NOI18N

        btn_barang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_barang.setForeground(new java.awt.Color(153, 153, 153));
        btn_barang.setText("Barang");
        btn_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_barangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_barangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_barangMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mn4Layout = new javax.swing.GroupLayout(mn4);
        mn4.setLayout(mn4Layout);
        mn4Layout.setHorizontalGroup(
            mn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ln4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        mn4Layout.setVerticalGroup(
            mn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn4Layout.createSequentialGroup()
                .addComponent(ln4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mn4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mn4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mn5.setBackground(new java.awt.Color(255, 255, 255));

        ln5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ln5Layout = new javax.swing.GroupLayout(ln5);
        ln5.setLayout(ln5Layout);
        ln5Layout.setHorizontalGroup(
            ln5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ln5Layout.setVerticalGroup(
            ln5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computer.png"))); // NOI18N

        btn_dashboard.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(153, 153, 153));
        btn_dashboard.setText("Dashboard");
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mn5Layout = new javax.swing.GroupLayout(mn5);
        mn5.setLayout(mn5Layout);
        mn5Layout.setHorizontalGroup(
            mn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ln5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        mn5Layout.setVerticalGroup(
            mn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn5Layout.createSequentialGroup()
                .addGroup(mn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ln5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mn5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(btn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mn6.setBackground(new java.awt.Color(255, 255, 255));

        ln6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ln6Layout = new javax.swing.GroupLayout(ln6);
        ln6.setLayout(ln6Layout);
        ln6Layout.setHorizontalGroup(
            ln6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ln6Layout.setVerticalGroup(
            ln6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/box.png"))); // NOI18N

        btn_BM.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_BM.setForeground(new java.awt.Color(153, 153, 153));
        btn_BM.setText("Barang Masuk");
        btn_BM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_BMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_BMMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mn6Layout = new javax.swing.GroupLayout(mn6);
        mn6.setLayout(mn6Layout);
        mn6Layout.setHorizontalGroup(
            mn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ln6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_BM, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        mn6Layout.setVerticalGroup(
            mn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn6Layout.createSequentialGroup()
                .addGroup(mn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ln6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mn6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(btn_BM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mn7.setBackground(new java.awt.Color(255, 255, 255));

        ln7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ln7Layout = new javax.swing.GroupLayout(ln7);
        ln7.setLayout(ln7Layout);
        ln7Layout.setHorizontalGroup(
            ln7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ln7Layout.setVerticalGroup(
            ln7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report.png"))); // NOI18N

        btn_pemesanan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_pemesanan.setForeground(new java.awt.Color(153, 153, 153));
        btn_pemesanan.setText("Pemesanan");
        btn_pemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pemesananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pemesananMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pemesananMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mn7Layout = new javax.swing.GroupLayout(mn7);
        mn7.setLayout(mn7Layout);
        mn7Layout.setHorizontalGroup(
            mn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ln7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        mn7Layout.setVerticalGroup(
            mn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn7Layout.createSequentialGroup()
                .addGroup(mn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ln7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mn7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(btn_pemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mn9.setBackground(new java.awt.Color(255, 255, 255));

        ln9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ln9Layout = new javax.swing.GroupLayout(ln9);
        ln9.setLayout(ln9Layout);
        ln9Layout.setHorizontalGroup(
            ln9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ln9Layout.setVerticalGroup(
            ln9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N

        btn_logout.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(153, 153, 153));
        btn_logout.setText("LogOut");
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mn9Layout = new javax.swing.GroupLayout(mn9);
        mn9.setLayout(mn9Layout);
        mn9Layout.setHorizontalGroup(
            mn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ln9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        mn9Layout.setVerticalGroup(
            mn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ln9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mn10.setBackground(new java.awt.Color(255, 255, 255));

        ln10.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ln10Layout = new javax.swing.GroupLayout(ln10);
        ln10.setLayout(ln10Layout);
        ln10Layout.setHorizontalGroup(
            ln10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ln10Layout.setVerticalGroup(
            ln10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/postal.png"))); // NOI18N

        btn_BK.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_BK.setForeground(new java.awt.Color(153, 153, 153));
        btn_BK.setText("Barang Keluar");
        btn_BK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_BKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_BKMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mn10Layout = new javax.swing.GroupLayout(mn10);
        mn10.setLayout(mn10Layout);
        mn10Layout.setHorizontalGroup(
            mn10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ln10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_BK, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        mn10Layout.setVerticalGroup(
            mn10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn10Layout.createSequentialGroup()
                .addGroup(mn10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ln10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mn10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mn10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(btn_BK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        mn13.setBackground(new java.awt.Color(255, 255, 255));

        ln13.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ln13Layout = new javax.swing.GroupLayout(ln13);
        ln13.setLayout(ln13Layout);
        ln13Layout.setHorizontalGroup(
            ln13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ln13Layout.setVerticalGroup(
            ln13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/postal.png"))); // NOI18N

        btn_LaporanMasuk.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_LaporanMasuk.setForeground(new java.awt.Color(153, 153, 153));
        btn_LaporanMasuk.setText("Laporan Masuk");
        btn_LaporanMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LaporanMasukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LaporanMasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LaporanMasukMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mn13Layout = new javax.swing.GroupLayout(mn13);
        mn13.setLayout(mn13Layout);
        mn13Layout.setHorizontalGroup(
            mn13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ln13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_LaporanMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mn13Layout.setVerticalGroup(
            mn13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mn13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btn_LaporanMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ln13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mn14.setBackground(new java.awt.Color(255, 255, 255));

        ln14.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ln14Layout = new javax.swing.GroupLayout(ln14);
        ln14.setLayout(ln14Layout);
        ln14Layout.setHorizontalGroup(
            ln14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ln14Layout.setVerticalGroup(
            ln14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/postal.png"))); // NOI18N

        btn_LaporanKeluar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_LaporanKeluar.setForeground(new java.awt.Color(153, 153, 153));
        btn_LaporanKeluar.setText("Laporan Keluar");
        btn_LaporanKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LaporanKeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LaporanKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LaporanKeluarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mn14Layout = new javax.swing.GroupLayout(mn14);
        mn14.setLayout(mn14Layout);
        mn14Layout.setHorizontalGroup(
            mn14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ln14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_LaporanKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        mn14Layout.setVerticalGroup(
            mn14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mn14Layout.createSequentialGroup()
                .addGroup(mn14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ln14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mn14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mn14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(btn_LaporanKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout scrollLayout = new javax.swing.GroupLayout(scroll);
        scroll.setLayout(scrollLayout);
        scrollLayout.setHorizontalGroup(
            scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scrollLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mn14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mn13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(scrollLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(mn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(scrollLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        scrollLayout.setVerticalGroup(
            scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scrollLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addComponent(mn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addComponent(mn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mn14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        scrollPaneWin111.setViewportView(scroll);

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        panel.add(sidebar, java.awt.BorderLayout.LINE_START);

        pn_dasar.setBackground(new java.awt.Color(250, 250, 250));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        panel.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_jenisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jenisMouseEntered
        // TODO add your handling code here:
        mn.setBackground(new Color(250, 250, 250));
        ln.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_jenisMouseEntered

    private void btn_jenisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jenisMouseExited
        // TODO add your handling code here:
        mn.setBackground(new Color(255, 255, 255));
        ln.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_jenisMouseExited

    private void btn_adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMouseEntered
        // TODO add your handling code here:
        mn1.setBackground(new Color(250, 250, 250));
        ln1.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_adminMouseEntered

    private void btn_adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMouseExited
        // TODO add your handling code here:
        mn1.setBackground(new Color(255, 255, 255));
        ln1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_adminMouseExited

    private void btn_supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supplierMouseEntered
        // TODO add your handling code here:
        mn2.setBackground(new Color(250, 250, 250));
        ln2.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_supplierMouseEntered

    private void btn_supplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supplierMouseExited
        // TODO add your handling code here:
        mn2.setBackground(new Color(255, 255, 255));
        ln2.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_supplierMouseExited

    private void btn_pemesanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemesanMouseEntered
        // TODO add your handling code here:
        mn3.setBackground(new Color(250, 250, 250));
        ln3.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_pemesanMouseEntered

    private void btn_pemesanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemesanMouseExited
        // TODO add your handling code here:
        mn3.setBackground(new Color(255, 255, 255));
        ln3.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_pemesanMouseExited

    private void btn_barangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMouseEntered
        // TODO add your handling code here:
        mn4.setBackground(new Color(250, 250, 250));
        ln4.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_barangMouseEntered

    private void btn_barangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMouseExited
        // TODO add your handling code here:
        mn4.setBackground(new Color(255, 255, 255));
        ln4.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_barangMouseExited

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        // TODO add your handling code here:
        mn5.setBackground(new Color(250, 250, 250));
        ln5.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
        // TODO add your handling code here:
        mn5.setBackground(new Color(255, 255, 255));
        ln5.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(new dashBoard());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pn_utama.add(new dashBoard());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    private void btn_jenisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jenisMouseClicked
        pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(new jenis_barang());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_jenisMouseClicked

    private void btn_BMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BMMouseClicked
         pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(new barang_masuk(lb_id.getText()));
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_BMMouseClicked

    private void btn_BMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BMMouseEntered
        mn6.setBackground(new Color(250, 250, 250));
        ln6.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_BMMouseEntered

    private void btn_BMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BMMouseExited
        mn6.setBackground(new Color(255, 255, 255));
        ln6.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_BMMouseExited

    private void btn_pemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemesananMouseClicked
        pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(new pesananSupply(lb_id.getText()));
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_pemesananMouseClicked

    private void btn_pemesananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemesananMouseEntered
        mn7.setBackground(new Color(250, 250, 250));
        ln7.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_pemesananMouseEntered

    private void btn_pemesananMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemesananMouseExited
        mn7.setBackground(new Color(255, 255, 255));
        ln7.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_pemesananMouseExited

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
       mn9.setBackground(new Color(250, 250, 250));
        ln9.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
       mn9.setBackground(new Color(255, 255, 255));
        ln9.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_BKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BKMouseClicked
         pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(new barang_keluar(lb_id.getText()));
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_BKMouseClicked

    private void btn_BKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BKMouseEntered
        mn10.setBackground(new Color(250, 250, 250));
        ln10.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_BKMouseEntered

    private void btn_BKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BKMouseExited
        mn10.setBackground(new Color(255, 255, 255));
        ln10.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_BKMouseExited

    private void btn_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMouseClicked
        pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(new barang());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_barangMouseClicked

    private void btn_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supplierMouseClicked
        pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(new supplier());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_supplierMouseClicked

    private void btn_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMouseClicked
        pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(new admin());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_adminMouseClicked

    private void btn_pemesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemesanMouseClicked
        pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(new pemesan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_pemesanMouseClicked

    private void btn_LaporanMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LaporanMasukMouseClicked
        pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(new Laporan_masuk());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_LaporanMasukMouseClicked

    private void btn_LaporanMasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LaporanMasukMouseEntered
        mn13.setBackground(new Color(250, 250, 250));
        ln13.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_LaporanMasukMouseEntered

    private void btn_LaporanMasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LaporanMasukMouseExited
        mn13.setBackground(new Color(255, 255, 255));
        ln13.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_LaporanMasukMouseExited

    private void btn_LaporanKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LaporanKeluarMouseClicked
 pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(new Laporan_keluar());
        pn_utama.repaint();
        pn_utama.revalidate();    }//GEN-LAST:event_btn_LaporanKeluarMouseClicked

    private void btn_LaporanKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LaporanKeluarMouseEntered
        mn14.setBackground(new Color(250, 250, 250));
        ln14.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_LaporanKeluarMouseEntered

    private void btn_LaporanKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LaporanKeluarMouseExited
        mn14.setBackground(new Color(255, 255, 255));
        ln14.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_LaporanKeluarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama("Id", "Nama","User").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_BK;
    private javax.swing.JLabel btn_BM;
    private javax.swing.JLabel btn_LaporanKeluar;
    private javax.swing.JLabel btn_LaporanMasuk;
    private javax.swing.JLabel btn_admin;
    private javax.swing.JLabel btn_barang;
    private javax.swing.JLabel btn_dashboard;
    private javax.swing.JLabel btn_jenis;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_pemesan;
    private javax.swing.JLabel btn_pemesanan;
    private javax.swing.JLabel btn_supplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_user;
    private javax.swing.JPanel ln;
    private javax.swing.JPanel ln1;
    private javax.swing.JPanel ln10;
    private javax.swing.JPanel ln13;
    private javax.swing.JPanel ln14;
    private javax.swing.JPanel ln2;
    private javax.swing.JPanel ln3;
    private javax.swing.JPanel ln4;
    private javax.swing.JPanel ln5;
    private javax.swing.JPanel ln6;
    private javax.swing.JPanel ln7;
    private javax.swing.JPanel ln9;
    private javax.swing.JPanel mn;
    private javax.swing.JPanel mn1;
    private javax.swing.JPanel mn10;
    private javax.swing.JPanel mn13;
    private javax.swing.JPanel mn14;
    private javax.swing.JPanel mn2;
    private javax.swing.JPanel mn3;
    private javax.swing.JPanel mn4;
    private javax.swing.JPanel mn5;
    private javax.swing.JPanel mn6;
    private javax.swing.JPanel mn7;
    private javax.swing.JPanel mn9;
    private jpanelgradient.JPanelGradient navbar;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JPanel scroll;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin111;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
